dev:
  app:
    name: "flaskeleton"
    version: "1.0.0"
    host: "127.0.0.1"
    port: 5005
    debug_mode: 1
  db:
    name: "flaskeleton.db"
    host: "127.0.0.1"
    port: 0000
    connection_string: "sqlite:///flaskeleton.db"

prod:
  app:
    name: "flaskeleton"
    version: "1.0.0"
    host: "0.0.0.0"
    port: 5005
    debug_mode: 0
  db:
    name: "flaskeleton.db"
    host: "127.0.0.1"
    port: 0000
    connection_string: "sqlite:///flaskeleton.db"

test:
  app:
    name: "flaskeleton"
    version: "1.0.0"
    host: "127.0.0.1"
    port: 5005
    debug_mode: 1
  db:
    name: "flaskeleton-test.db"
    host: "127.0.0.1"
    port: 0000
    connection_string: "sqlite:///flaskeleton-test.db"
