dev:
  app:
    name: "flaskeleton"
    version: "1.0.0"
    host: "127.0.0.1"
    port: 5005
    debug_mode: 1
  db:
    name: "flaskeleton"
    host: "127.0.0.1"
    port: 0000
    connection_string: "mysql+pymysql://root:root@localhost/flaskeleton"

prod:
  app:
    name: "flaskeleton"
    version: "1.0.0"
    host: "0.0.0.0"
    port: 5005
    debug_mode: 0
  db:
    name: "flaskeleton"
    host: "flaskeletondb"
    port: 0000
    connection_string: "mysql+pymysql://root:root@flaskeletondb/flaskeleton"

test:
  app:
    name: "flaskeleton"
    version: "1.0.0"
    host: "127.0.0.1"
    port: 5005
    debug_mode: 1
  db:
    name: "flaskeleton_test"
    host: "127.0.0.1"
    port: 0000
    connection_string: "mysql+pymysql://root:root@localhost/flaskeleton_test"
